chore: update style
Weaverse/naturelle pull request #53
Opened 2024-05-06 09:54 UTC by dangthang1903

2024-05-07 08:15 UTC, viethung26 commented on app/sections/feature-product/index.tsx
> +    BackgroundColor: string;
nên đặt props theo camelCase

2024-05-07 08:17 UTC, viethung26 requested changes
pls check my comment

2024-05-07 08:19 UTC, dangthang1903 commented on app/sections/feature-product/index.tsx
> +    BackgroundColor: string;
em sửa lại rồi ạ

2024-05-08 02:28 UTC, hta218 approved these changes

2024-05-08 02:28 UTC, merged